name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.15.0+1
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  google_sign_in: ^4.4.4
  flutter_signin_button: ^1.0.0
  http: ^0.12.1
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  video_player: ^0.10.10
  flutter_rating_bar: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^0.4.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AppIcon.png"

flutter_launcher_name:
  name: "Moga Movies"

flutter:

  uses-material-design: true

  assets:
    - assets/images/